[package]
name = "backend"
authors = ["Kristi Fidani ğŸ¦"]
version = "0.1.0"
edition = "2024"
rust-version = "1.89"

[lints.clippy]
# With these two, we avoid panicking behavior in our code.
# In some places where panicking is desired, such as in tests or in the `main.rs` files,
# these are allowed using #[allow(clippy::unwrap_used, clippy::expect_used] or configured
# to be allowed in the `.clippy.toml` config file.
unwrap_used = "deny"
expect_used = "deny"

[dependencies]
actix-web = { version = "4", default-features = false, features = ["macros"] }
dotenvy = { version = "0.15", default-features = false }
mongodb = { version = "3.2.4", default-features = false, features = [
    "rustls-tls",
    "compat-3-0-0",
] }
reqwest = { version = "0.12.23", default-features = false, features = ["json"] }
serde = { version = "1.0.217", default-features = false, features = ["derive"] }
async-trait = { version = "0.1.88", default-features = false }
serde_json = { version = "1.0.142", default-features = false }
url = { version = "2", default-features = false, features = ["serde"] }

# error handling
thiserror = { version = "2.0.14", default-features = false }

# tracing
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "env-filter",
    "fmt",
] }

[dev-dependencies]
rstest = { version = "0.26.1", default-features = false }
mockito = { version = "1.6", default-features = false }
tokio = { version = "1.47.1", default-features = false }


[[bin]]
name = "rest-api"
path = "bin/main.rs"
